<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JKTNOLAP622" failures="1" tests="2" name="Test" time="34.369" errors="0" timestamp="08 Jan 2024 10:43:46 GMT">
  <testcase classname="com.jktech.TestCases.LoginTest" name="validLoginTest" time="5.389"/>
  <testcase classname="com.jktech.TestCases.LoginTest" name="validLoginTest" time="5.831">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at com.jktech.TestCases.LoginTest.validLoginTest(LoginTest.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- Test -->
