<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JKTNOLAP622" failures="1" tests="1" name="Test(failed)" time="21.402" errors="0" timestamp="08 Jan 2024 10:44:41 GMT">
  <testcase classname="com.jktech.TestCases.LoginTest" name="validLoginTest" time="6.044">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at com.jktech.TestCases.LoginTest.validLoginTest(LoginTest.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- Test(failed) -->
